joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

camera_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: support_camera_joint
  pid: {p: 2.0, i: 0.0, d: 0.0}
  
  

